# Generated by Django 4.2.3 on 2024-03-14 07:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=99, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=99, verbose_name='Balance'),
        ),
    ]
