# Generated by Django 4.2.3 on 2024-03-18 08:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_request_remove_basketproduct_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='give_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=99, verbose_name='Give price'),
        ),
    ]
