# Generated by Django 4.2.3 on 2024-03-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_product_give_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='give_price',
            new_name='pay',
        ),
    ]
