# Generated by Django 4.2.3 on 2024-03-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_district_name_alter_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='code',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
