# Generated by Django 4.2.3 on 2024-03-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_attribute_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='code',
        ),
    ]
