# Generated by Django 4.2.3 on 2024-03-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_attribute_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='code',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
