# Generated by Django 4.2.3 on 2024-03-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_attribute_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_color', to='apps.productattribute', verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_size', to='apps.productattribute', verbose_name='color'),
            preserve_default=False,
        ),
    ]
