# Generated by Django 4.2.3 on 2024-03-22 10:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_order_color_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=99, verbose_name='price'),
        ),
    ]
