# Generated by Django 4.2.3 on 2024-03-28 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('waiting', 'Waiting')], default='waiting', max_length=20),
        ),
    ]
