# Generated by Django 4.2.3 on 2024-04-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_request_date_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.region', verbose_name='region'),
        ),
    ]
