# Generated by Django 4.2.3 on 2024-04-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_request_date_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
